[tool.black]
line-length = 140
target-version = ["py310"]
extend-exclude = '(\.venv|docs)'

[tool.ruff]
line-length = 140
target-version = "py310"
extend-exclude = [".venv", "docs"]

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort (imports)
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "C4",  # flake8-comprehensions
  "W",   # pycodestyle warnings
  "SIM"  # flake8-simplify
]
ignore = [
  "E203", # whitespace before ':' (black-compat)
  "E501", # let black handle line length
]

[tool.ruff.format]
docstring-code-format = true

[tool.isort]
profile = "black"
line_length = 140
skip = [".venv", "docs"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
strict_optional = true
files = ["src"]

[[tool.mypy.overrides]]
module = ["src.text_complexity_improved", "src.text_complexity_children_optimized"]
ignore_errors = true

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests"]

